title: Contributing to Open Source
author: Claudia Maciel
theme: minima
email: claudia@thecoderpilot.com
description: > # this means to ignore newlines until "baseurl:"
  Figuring out how to contribute to open source and blogging about i. 

# social links
twitter_username: @clc_80
github_username:  clc80

show_excerpts: true # set to false to remove excerpts on the homepage
